export interface EventItem {
  id: string;
  title: string;
  date: string;
  description: string;
  thumbnail: string;
  status: "completed" | "upcoming" | "coming-soon";
  organizationType?: "ORGANIZED" | "CONTRIBUTED";
  link?: string;
  featured?: boolean;
}

const rawEvents: EventItem[] = [
  {
    id: "ai-hackathon-i",
    title: "AI Hackathon I",
    date: "2025-03-08",
    description: "Our first AI hackathon bringing builders together for rapid prototyping.",
    thumbnail: "/ai-hackathon-i/1.png",
    status: "completed",
    organizationType: "ORGANIZED",
    featured: true,
  },
  {
    id: "ai-hackathon-ii",
    title: "AI Hackathon II",
    date: "2025-05-10",
    description: "Second edition with stronger projects, demos, and team momentum.",
    thumbnail: "/ai-hackathon-ii/2.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
    featured: true,
  },
  {
    id: "signal-i",
    title: "SIGNAL I",
    date: "2025-06-05",
    description: "Our first SIGNAL meetup focused on practical lessons from real builders.",
    thumbnail: "/signal-i/1.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
    featured: true,
  },
  {
    id: "robotics-hackathon-i",
    title: "Robotics Hackathon I",
    date: "2025-06-14",
    description: "Hands-on robotics weekend focused on building and shipping working systems.",
    thumbnail: "/robotics-i/1.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
    featured: true,
  },
  {
    id: "signal-ii",
    title: "SIGNAL II",
    date: "2025-08-21",
    description: "Second SIGNAL gathering for founders, engineers, and researchers.",
    thumbnail: "/signal-ii/1.png",
    status: "completed",
    organizationType: "ORGANIZED",
    featured: true,
  },
  {
    id: "ai-hackathon-iii",
    title: "AI Hackathon III",
    date: "2025-08-30",
    description: "Third AI hackathon with stronger multi-agent and product-focused builds.",
    thumbnail: "/ai-hackathon-iii/10.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
    featured: true,
  },
  {
    id: "brucon",
    title: "BruCon Security Conference",
    date: "2025-09-25",
    description: "Belgium's premier security conference where we contributed with the North Star team.",
    thumbnail: "/partnerships/logos/2.png",
    status: "completed",
    organizationType: "CONTRIBUTED",
  },
  {
    id: "kids-ai-vibecoding-hackathon",
    title: "Kids AI Vibecoding Hackathon",
    date: "2025-10-11",
    description: "Youth-focused AI coding day introducing kids to building with AI tools.",
    thumbnail: "/kids-hackathon/1.png",
    status: "completed",
    organizationType: "ORGANIZED",
    featured: true,
  },
  {
    id: "future-in-bloom-pt1",
    title: "Future In Bloom Pt. I",
    date: "2025-10-18",
    description: "Embodied AI coworking and build sessions pushing practical robotics work forward.",
    thumbnail: "/future-in-bloom/1.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
    featured: true,
  },
  {
    id: "tectonic",
    title: "Tectonic",
    date: "2025-11-05",
    description: "Major Belgian tech conference where we contributed to ecosystem-level programming.",
    thumbnail: "/tectonic/tectonic.jpeg",
    status: "completed",
    organizationType: "CONTRIBUTED",
    featured: true,
  },
  {
    id: "belgium-nlp-meetup-27",
    title: "27th Belgium NLP Meetup",
    date: "2025-11-20",
    description: "AI and multi-agent systems meetup centered on production-ready systems and real-world demos.",
    thumbnail: "/belgium-nlp-meetup/1.avif",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "stripe-hackathon",
    title: "Agentic Payments Hackathon with Stripe",
    date: "2025-11-22",
    description: "A payments-focused build weekend for agentic checkout and automation experiments.",
    thumbnail: "/stripe-hackathon/1.png",
    status: "completed",
    organizationType: "ORGANIZED",
    featured: true,
  },
  {
    id: "get-sip-done-antwerp",
    title: "Get Sip Done: Antwerp Kick-Off",
    date: "2025-11-28",
    description: "A founder breakfast connecting Antwerp builders, operators, and investors.",
    thumbnail: "/get-sip-done/1.png",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "elevenlabs-hackathon-ghent",
    title: "ElevenLabs Worldwide Hackathon (Community Edition)",
    date: "2025-12-11",
    description: "A community edition of the ElevenLabs global hackathon with voice AI builders in Ghent.",
    thumbnail: "/elevenlabs/1.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
    featured: true,
  },
  {
    id: "signal-iii",
    title: "SIGNAL III",
    date: "2026-01-29",
    description: "Flagship SIGNAL meetup featuring high-signal talks and demos.",
    thumbnail: "/signal.jpeg",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "ap-robotics-workshop",
    title: "University Robotics Workshop",
    date: "2026-02-10",
    description: "Hands-on SO-101 robotics workshop at AP Hogeschool Antwerpen covering the LeRobot ecosystem, VLAs, and imitation learning workflows.",
    thumbnail: "/ap-workshop/photo_2026-03-08 19.50.40.jpeg",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "openclaw-meetup",
    title: "OpenClaw Deep Dive",
    date: "2026-02-25",
    description: "An open evening for builders in collaboration with ICP Belgium, featuring a talk and live stations on OpenClaw AI agents.",
    thumbnail: "/openclaw-meetup/photo_2026-03-08 19.28.34.jpeg",
    status: "completed",
    organizationType: "CONTRIBUTED",
  },
  {
    id: "ai-community-journal-club-001",
    title: "AI Community Journal Club #001",
    date: "2026-02-26",
    description: "A recurring paper-reading evening by AI Belgium and North Star.",
    thumbnail: "/journal-club-1/photo_2026-03-08 19.28.17.jpeg",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "openlab-vessel-1",
    title: "OpenLab @ The Vessel",
    date: "2026-03-19",
    description: "First Open Lab Thursday at our new AI & Robotics lab in the Antwerp port area.",
    thumbnail: "/blogs/the-vessel/2026-03-10 16.58.10.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
    link: "/blog/the-vessel",
  },
  {
    id: "ai-community-journal-club-002",
    title: "AI Community Journal Club #002",
    date: "2026-03-30",
    description: "Second edition of the recurring paper-reading evening by AI Belgium and North Star. Presenters introduce peer-reviewed AI papers with Q&A.",
    thumbnail: "/journal-club-1/photo_2026-03-08 19.28.17.jpeg",
    status: "completed",
    organizationType: "ORGANIZED",
    link: "https://etoile.events/events/15826288-4f22-43d3-b0ab-7ac24d7758be",
  },
  {
    id: "benelux-robotics-meetup",
    title: "Benelux Robotics Meetup",
    date: "2026-05-12",
    description: "Our first event outside Belgium. A sold-out night at TU/e Eindhoven on how the Benelux becomes a serious force in robotics.",
    thumbnail: "/benelux-robotics/1.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
    featured: true,
  },
  {
    id: "techxperience-openclaw-workshop",
    title: "TechXperience: OpenClaw Workshop",
    date: "2026-05-21",
    description: "Lunch workshop at The Beacon: a hands-on OpenClaw session by North Star covering AI agent architecture, memory, failure modes, and practical automation workflows.",
    thumbnail: "/techxperience/cover.png",
    status: "completed",
    organizationType: "ORGANIZED",
    link: "https://www.eventbrite.be/e/techxperience-battle-of-the-ais-openclaw-tickets-1985714555690",
    featured: true,
  },
  {
    id: "hackers-and-ravers",
    title: "Hackers & Ravers",
    date: "2026-05-30",
    description: "12-hour AI hackathon fused with a proper rave inside the Wintercircus dome in Ghent. Co-organised by Soda and Wintercircus, with North Star as a partner.",
    thumbnail: "/hackers-and-ravers/cover.jpeg",
    status: "completed",
    organizationType: "CONTRIBUTED",
    featured: true,
  },
  {
    id: "hack-nation-brussels",
    title: "Hack-Nation Global AI Hackathon: Brussels Hub",
    date: "2026-07-18",
    description: "With WAT.BXL, North Star brings Hack-Nation's Global AI Hackathon to Brussels. 50 seats alongside teams from MIT, Stanford, Munich, London, Zurich and beyond. $35K+ in prizes and $200K in API credits.",
    thumbnail: "/hacknation/cover.jpeg",
    status: "upcoming",
    organizationType: "ORGANIZED",
    link: "https://hack-nation.ai/",
    featured: true,
  },
  {
    id: "openai-codex-meetup",
    title: "OpenAI Codex Community Meetup",
    date: "2026-06-22",
    description: "Belgium's first OpenAI Codex Community Meetup at Wintercircus Ghent: Codex updates, live demos, an agents session, and an on-site OpenAI engineer AMA.",
    thumbnail: "/codex-meetup/cover.jpeg",
    status: "completed",
    organizationType: "ORGANIZED",
    link: "https://luma.com/ofb4ell6",
    featured: true,
  },
  {
    id: "openai-codex-meetup-antwerp",
    title: "OpenAI Codex Community Meetup — Antwerp",
    date: "2026-06-27",
    description: "Antwerp edition of the OpenAI Codex Community Meetup at The Vessel: Codex updates, live demos, and an agents session with the Belgian builder community.",
    thumbnail: "/codex-meetup-antwerp/cover.jpeg",
    status: "upcoming",
    organizationType: "ORGANIZED",
    link: "https://luma.com/j0d0zl2q",
    featured: true,
  },
  {
    id: "robib-wat-bxl",
    title: "Robotics in Belgium @ WAT.BXL",
    date: "2026-06-24",
    description: "ROBIB's second edition at WAT.BXL in Brussels: lightning talks, a panel on where robotics is heading, startup pitches, and drinks. North Star joins as community partner.",
    thumbnail: "/robib/cover.jpeg",
    status: "upcoming",
    organizationType: "CONTRIBUTED",
    link: "https://luma.com/4x89l3eh",
  },
  {
    id: "schip-stem-zomerkamp",
    title: "SCHIP: STEM-zomerkamp rond AI en robotica",
    date: "2026-07-03",
    description: "A five-day STEM summer camp (3–7 July) at The Vessel where kids aged 12–16 explore AI, robotics, and coding through real Port of Antwerp challenges.",
    thumbnail: "/schip/cover.jpg",
    status: "upcoming",
    organizationType: "ORGANIZED",
    link: "https://luma.com/ss0fizxj",
    featured: true,
  },
];

const todayISO = new Date().toISOString().slice(0, 10);

export const allEvents: EventItem[] = rawEvents.map((event) =>
  event.status !== "coming-soon" && event.date < todayISO
    ? { ...event, status: "completed" }
    : event,
);

export const completedEvents = allEvents.filter((event) => event.status === "completed");
export const upcomingEvents = allEvents.filter((event) => event.status === "upcoming");
