export interface EventItem {
  id: string;
  title: string;
  date: string;
  description: string;
  thumbnail: string;
  status: "completed" | "upcoming" | "coming-soon";
  organizationType?: "ORGANIZED" | "CONTRIBUTED";
  link?: string;
}

export const allEvents: EventItem[] = [
  {
    id: "ai-hackathon-i",
    title: "AI Hackathon I",
    date: "2025-03-08",
    description: "Our first AI hackathon bringing builders together for rapid prototyping.",
    thumbnail: "/ai-hackathon-i/1.png",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "ai-hackathon-ii",
    title: "AI Hackathon II",
    date: "2025-05-10",
    description: "Second edition with stronger projects, demos, and team momentum.",
    thumbnail: "/ai-hackathon-ii/2.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "signal-i",
    title: "SIGNAL I",
    date: "2025-06-05",
    description: "Our first SIGNAL meetup focused on practical lessons from real builders.",
    thumbnail: "/signal-i/1.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "robotics-hackathon-i",
    title: "Robotics Hackathon I",
    date: "2025-06-14",
    description: "Hands-on robotics weekend focused on building and shipping working systems.",
    thumbnail: "/robotics-i/1.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "signal-ii",
    title: "SIGNAL II",
    date: "2025-08-21",
    description: "Second SIGNAL gathering for founders, engineers, and researchers.",
    thumbnail: "/signal-ii/1.png",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "ai-hackathon-iii",
    title: "AI Hackathon III",
    date: "2025-08-30",
    description: "Third AI hackathon with stronger multi-agent and product-focused builds.",
    thumbnail: "/ai-hackathon-iii/10.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "brucon",
    title: "BruCon Security Conference",
    date: "2025-09-25",
    description: "Belgium's premier security conference where we contributed with the North Star team.",
    thumbnail: "/partnerships/logos/2.png",
    status: "completed",
    organizationType: "CONTRIBUTED",
  },
  {
    id: "kids-ai-vibecoding-hackathon",
    title: "Kids AI Vibecoding Hackathon",
    date: "2025-10-11",
    description: "Youth-focused AI coding day introducing kids to building with AI tools.",
    thumbnail: "/kids-hackathon/1.png",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "future-in-bloom-pt1",
    title: "Future In Bloom Pt. I",
    date: "2025-10-18",
    description: "Embodied AI coworking and build sessions pushing practical robotics work forward.",
    thumbnail: "/future-in-bloom/1.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "tectonic",
    title: "Tectonic",
    date: "2025-11-05",
    description: "Major Belgian tech conference where we contributed to ecosystem-level programming.",
    thumbnail: "/tectonic/tectonic.jpeg",
    status: "completed",
    organizationType: "CONTRIBUTED",
  },
  {
    id: "belgium-nlp-meetup-27",
    title: "27th Belgium NLP Meetup",
    date: "2025-11-20",
    description: "AI and multi-agent systems meetup centered on production-ready systems and real-world demos.",
    thumbnail: "/belgium-nlp-meetup/1.avif",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "stripe-hackathon",
    title: "Agentic Payments Hackathon with Stripe",
    date: "2025-11-22",
    description: "A payments-focused build weekend for agentic checkout and automation experiments.",
    thumbnail: "/stripe-hackathon/1.png",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "get-sip-done-antwerp",
    title: "Get Sip Done: Antwerp Kick-Off",
    date: "2025-11-28",
    description: "A founder breakfast connecting Antwerp builders, operators, and investors.",
    thumbnail: "/get-sip-done/1.png",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "elevenlabs-hackathon-ghent",
    title: "ElevenLabs Worldwide Hackathon (Community Edition)",
    date: "2025-12-11",
    description: "A community edition of the ElevenLabs global hackathon with voice AI builders in Ghent.",
    thumbnail: "/elevenlabs/1.jpg",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "signal-iii",
    title: "SIGNAL III",
    date: "2026-01-29",
    description: "Flagship SIGNAL meetup featuring high-signal talks and demos.",
    thumbnail: "/signal-iii/1.png",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "ap-robotics-workshop",
    title: "University Robotics Workshop",
    date: "2026-02-10",
    description: "Hands-on SO-101 robotics workshop at AP Hogeschool Antwerpen covering the LeRobot ecosystem, VLAs, and imitation learning workflows.",
    thumbnail: "/ap-workshop/photo_2026-03-08 19.50.40.jpeg",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "openclaw-meetup",
    title: "OpenClaw Deep Dive",
    date: "2026-02-25",
    description: "An open evening for builders in collaboration with ICP Belgium, featuring a talk and live stations on OpenClaw AI agents.",
    thumbnail: "/openclaw-meetup/photo_2026-03-08 19.28.34.jpeg",
    status: "completed",
    organizationType: "CONTRIBUTED",
  },
  {
    id: "ai-community-journal-club-001",
    title: "AI Community Journal Club #001",
    date: "2026-02-26",
    description: "A recurring paper-reading evening by AI Belgium and North Star.",
    thumbnail: "/journal-club-1/photo_2026-03-08 19.28.17.jpeg",
    status: "completed",
    organizationType: "ORGANIZED",
  },
  {
    id: "openlab-vessel-1",
    title: "OpenLab @ The Vessel",
    date: "2026-03-19",
    description: "First Open Lab Thursday at our new AI & Robotics lab in the Antwerp port area.",
    thumbnail: "/blogs/the-vessel/2026-03-10 16.58.10.jpg",
    status: "upcoming" as const,
    organizationType: "ORGANIZED",
    link: "/blog/the-vessel",
  },
  {
    id: "ai-community-journal-club-002",
    title: "AI Community Journal Club #002",
    date: "2026-03-30",
    description: "Second edition of the recurring paper-reading evening by AI Belgium and North Star. Presenters introduce peer-reviewed AI papers with Q&A.",
    thumbnail: "/journal-club-1/photo_2026-03-08 19.28.17.jpeg",
    status: "upcoming" as const,
    organizationType: "ORGANIZED",
    link: "https://etoile.events/events/15826288-4f22-43d3-b0ab-7ac24d7758be",
  },
];

export const completedEvents = allEvents.filter((event) => event.status === "completed");
